apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  SUPABASE_SERVICE_ROLE_KEY: <YOUR_SUPABASE_SERVICE_ROLE_KEY>
  SUPABASE_ANON_KEY: <YOUR_SUPABASE_ANON_KEY>
  JWT_SECRET: <YOUR_JWT_SECRET>
  GEMINI_API_KEY: <YOUR_GEMINI_API_KEY>