apiVersion: apps/v1
kind: Deployment

metadata:
  name: satiety-frontend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: satiety-frontend

  template:
    metadata:
      labels:
        app: satiety-frontend

    spec:
      containers:
        - name: frontend

          image: triptipcode/satiety-frontend:latest

          imagePullPolicy: Always

          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"          

          ports:
            - containerPort: 80