apiVersion: v1
kind: Service

metadata:
  name: satiety-frontend-service

spec:
  selector:
    app: satiety-frontend

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: ClusterIP