name: Deploy Version

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      #################################################
      # Determine version from selected Git tag
      #################################################

      - name: Get Version
        id: version
        shell: pwsh
        run: |
          $version = "${{ github.ref_name }}"
          echo "VERSION=$version" >> $env:GITHUB_ENV

      #################################################
      # Apply Kubernetes manifests
      #################################################

      - name: Apply Kubernetes manifests
        shell: pwsh
        run: |
          # Do not apply backend-secret.yaml: it is a template with placeholder values.
          kubectl apply -f k8s/backend-configmap.yaml
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/backend-service.yaml
          kubectl apply -f k8s/backend-servicemonitor.yaml
          kubectl apply -f k8s/backend-hpa.yaml
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml
          kubectl apply -f k8s/frontend-hpa.yaml
          kubectl apply -f k8s/ingress.yaml

      #################################################
      # Deploy Frontend
      #################################################

      - name: Deploy Frontend
        shell: pwsh
        run: |
          kubectl set image deployment/satiety-frontend `
          frontend=${{ secrets.DOCKER_USERNAME }}/satiety-frontend:$env:VERSION

      #################################################
      # Deploy Backend
      #################################################

      - name: Deploy Backend
        shell: pwsh
        run: |
          kubectl set image deployment/satiety-backend `
          backend=${{ secrets.DOCKER_USERNAME }}/satiety-backend:$env:VERSION

      #################################################
      # Wait for rollout
      #################################################

      - name: Wait Frontend
        shell: pwsh
        run: kubectl rollout status deployment/satiety-frontend

      - name: Wait Backend
        shell: pwsh
        run: kubectl rollout status deployment/satiety-backend

      #################################################
      # Verify
      #################################################

      - name: Show Images
        shell: pwsh
        run: |
          kubectl get deploy
          kubectl describe deployment satiety-backend
          kubectl describe deployment satiety-frontend
